elk:
  image: sebp/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  environment:
    - MAX_MAP_COUNT=262144
  volumes:
    - /Volumes/Samsung_T5/docker-volumes/elk:/var/lib/elasticsearch

#docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it -e MAX_MAP_COUNT=262144   -v elk-data:/var/lib/elasticsearch --name elk sebp/elk